import { constants } from 'node:fs'
import { access, mkdir, readdir, readFile, rename, rm, writeFile } from 'node:fs/promises'
import { basename, dirname, join, relative, sep } from 'node:path'
import type { CollectionDefinition, ResolvedConfig, StoreEntry } from '../types.ts'
import { digest } from '../utils/digest.ts'
import { withFdRetry } from '../utils/fd.ts'
import { mapLimit } from '../utils/limit.ts'
import { toPosix } from '../utils/paths.ts'
import type { DiagnosticBag } from '../diagnostics/index.ts'
import { moduleNameFor, serialize, SerializeError, serializeAt } from './serialize.ts'

export interface EmitStats {
  written: number
  skipped: number
  /**
   * Digest of the content last written to each path, plus the source digest
   * that produced it. Lets a rebuild skip serialization entirely for documents
   * whose source has not changed — without it, an incremental build still pays
   * to re-serialize and re-read the whole corpus, which is precisely why a
   * one-character edit costs content-collections ~2 seconds.
   */
  /** `check` validates without producing artifacts. */
  dryRun: boolean
  emitted: Map<string, string>
  sources: Map<string, string>
  /** Serialized index-row fragments, keyed by output path. */
  rows: Map<string, string>
}

export function createEmitStats(dryRun = false): EmitStats {
  return { dryRun, written: 0, skipped: 0, emitted: new Map(), sources: new Map(), rows: new Map() }
}

/**
 * Write output, skipping files whose bytes are unchanged.
 *
 * The skip matters for DX, not just speed: rewriting an identical file bumps
 * its mtime, which makes Vite and Next fire a spurious HMR update. We also
 * probe with access() rather than trusting an in-memory record — velite's
 * emitted-map is memory-only, so a file deleted outside the process is never
 * restored.
 */
export async function emit(
  path: string,
  content: string,
  stats: EmitStats,
  present?: ReadonlySet<string>
): Promise<void> {
  if (stats.dryRun) {
    stats.skipped++
    return
  }
  const hash = digest(content)
  if (stats.emitted.get(path) === hash) {
    // We wrote exactly these bytes this session. Confirm the file is still
    // there — velite trusts an in-memory map alone, so a file deleted outside
    // the process is never restored — but skip the far costlier read+compare.
    const there = present ? present.has(basename(path)) : await exists(path)
    if (there) {
      stats.skipped++
      return
    }
  } else {
    try {
      if ((await withFdRetry(() => readFile(path, 'utf8'))) === content) {
        stats.emitted.set(path, hash)
        stats.skipped++
        return
      }
    } catch {
      // missing or unreadable — fall through and write
    }
  }
  await mkdir(dirname(path), { recursive: true })
  const tmp = `${path}.${process.pid}.tmp`
  await withFdRetry(() => writeFile(tmp, content, 'utf8'))
  await withFdRetry(() => rename(tmp, path))
  stats.emitted.set(path, hash)
  stats.written++
}

export async function exists(path: string): Promise<boolean> {
  try {
    await access(path, constants.F_OK)
    return true
  } catch {
    return false
  }
}

const BANNER = '// Generated by contentmap. Do not edit.\n'

/** Writes are cheaper than reads; the same bound keeps descriptors in check. */
const WRITE_CONCURRENCY = 64

function splitFields(
  entry: StoreEntry,
  collection: CollectionDefinition
): { index: Record<string, unknown>; full: Record<string, unknown> } {
  const heavy = new Set(collection.heavy ?? [])
  const allow = collection.index ? new Set(collection.index) : undefined
  // The document module carries full provenance; the index carries only what a
  // list view plausibly needs. `digest` is build-internal and must never ship,
  // and fileName/directory/extension are all derivable from filePath — at 5,000
  // documents those four fields alone dominated the index.
  const { digest: _digest, ...meta } = entry.meta
  const full: Record<string, unknown> = { ...entry.data, _meta: meta }
  const index: Record<string, unknown> = {}
  for (const [k, v] of Object.entries(entry.data)) {
    if (heavy.has(k)) continue
    if (allow && !allow.has(k)) continue
    index[k] = v
  }
  index['_meta'] = {
    id: meta.id,
    path: meta.path,
    slug: meta.slug,
    filePath: meta.filePath
  }
  return { index, full }
}

export interface EmitCollectionInput {
  collection: CollectionDefinition
  entries: readonly StoreEntry[]
  config: ResolvedConfig
  stats: EmitStats
  diagnostics: DiagnosticBag
}

/** One module per document plus a thin index that lazily imports them. */
export async function emitCollection({
  collection,
  entries,
  config,
  stats,
  diagnostics
}: EmitCollectionInput): Promise<void> {
  const dir = join(config.output.dir, collection.name)
  if (!stats.dryRun) await mkdir(dir, { recursive: true })

  // One readdir replaces one access() per document. On a 10k corpus that is a
  // single syscall instead of ten thousand, it still catches files deleted
  // outside the process, and it gives us the set needed to remove orphans.
  const present = stats.dryRun
    ? new Set<string>()
    : new Set<string>(await withFdRetry(() => readdir(dir)).catch(() => []))

  const format = collection.format ?? config.output.format
  const emitModules = format === 'modules' || format === 'both'

  // A singleton collapses to one document, so per-document modules and a
  // queryable index would both be ceremony around a single object.
  if (collection.single) {
    const doc = entries[0]
    const body = doc === undefined ? 'undefined' : serialize(splitFields(doc, collection).full)
    const source =
      `${BANNER}export const ${collection.name} = ${body}\n` + `export default ${collection.name}\n`
    await emit(join(dir, 'index.js'), source, stats)
    await removeOrphans(dir, present, new Set(), stats)
    return
  }

  const indexRows: string[] = []
  const loaders: string[] = []
  const expected = new Set<string>(['index.js'])

  const work = entries.map(entry => {
    const mod = moduleNameFor(entry.id)
    const file = `${mod}.js`
    const path = join(dir, file)
    // emitKey, not digest: output depends on referenced assets too.
    const fresh = stats.sources.get(path) !== entry.emitKey

    // Reuse the serialized index fragment when the source is unchanged. This is
    // what makes an incremental rebuild cost one row rather than the corpus.
    let row = fresh ? undefined : stats.rows.get(path)
    let full: Record<string, unknown> | undefined
    if (row === undefined) {
      try {
        const split = splitFields(entry, collection)
        full = split.full
        row = serializeAt(emitModules ? split.index : split.full, 1)
      } catch (error) {
        // A transform that returns something unemittable is a problem with one
        // document, not with the build. Naming the file and dropping the
        // document beats an unattributed crash — velite's `s.isodate()` throws
        // a bare RangeError with no filename, which on a large corpus is
        // unsearchable.
        diagnostics.add({
          code: 'CM_SERIALIZE',
          severity: 'error',
          message: error instanceof SerializeError ? error.message : String(error),
          file: entry.meta.filePath,
          collection: collection.name,
          documentId: entry.id,
          ...(error instanceof SerializeError && error.path !== '$'
            ? { field: error.path.replace(/^\$\.?/, '') }
            : {}),
          hint: 'Documents are written to disk as JavaScript. Return plain data from `transform`.'
        })
        return undefined
      }
      stats.rows.set(path, row)
    }
    indexRows.push(row)
    if (!emitModules) return undefined
    expected.add(file)
    loaders.push(`  ${JSON.stringify(entry.id)}: () => import('./${file}')`)
    return { entry, full, path }
  })

  if (emitModules) {
    // Bounded-parallel, not serial. Ten thousand sequential awaits was 88% of a
    // cold build; the filesystem is happy to take these concurrently.
    await mapLimit(work, WRITE_CONCURRENCY, async item => {
      if (!item) return
      // Output is a pure function of the source, so an unchanged source digest
      // means unchanged output. Skipping serialize here keeps an incremental
      // rebuild proportional to what changed, not to corpus size.
      if (stats.sources.get(item.path) === item.entry.emitKey && present.has(basename(item.path))) {
        stats.skipped++
        return
      }
      const full = item.full ?? splitFields(item.entry, collection).full
      await emit(item.path, `${BANNER}export default ${serialize(full)}\n`, stats, present)
      stats.sources.set(item.path, item.entry.emitKey)
    })
  }

  // `bundle` inlines whole documents instead of lazily importing them, but it
  // exposes the SAME Query object. Handing back a bare array here — as the
  // first cut did — would make the emitted `.d.ts` lie about the runtime shape
  // the moment a collection opted into bundling.
  const parts = [
    BANNER,
    `import { collection } from 'contentmap/runtime'\n\n`,
    `const index = [\n${indexRows.join(',\n')}\n]\n\n`,
    `const modules = {\n${loaders.join(',\n')}\n}\n\n`,
    `export const ${collection.name} = collection(index, modules)\n`,
    `export default ${collection.name}\n`
  ]
  await emit(join(dir, 'index.js'), parts.join(''), stats)
  await removeOrphans(dir, present, expected, stats)
}

/**
 * Delete generated modules whose document no longer exists.
 *
 * Without this, renaming or deleting content leaves the old module on disk
 * forever. It is unreferenced by the index so nothing breaks at runtime, but it
 * bloats deploys and confuses anyone reading the output directory.
 */
async function removeOrphans(
  dir: string,
  present: ReadonlySet<string>,
  expected: ReadonlySet<string>,
  stats: EmitStats
): Promise<void> {
  if (stats.dryRun) return
  const stale = [...present].filter(
    name => name.endsWith('.js') && !expected.has(name) && name !== 'index.js'
  )
  if (stale.length === 0) return
  await mapLimit(stale, WRITE_CONCURRENCY, async name => {
    const path = join(dir, name)
    await rm(path, { force: true })
    stats.emitted.delete(path)
    stats.sources.delete(path)
    stats.rows.delete(path)
  })
}

export async function emitBarrel(config: ResolvedConfig, stats: EmitStats): Promise<void> {
  const names = Object.keys(config.collections)
  const lines = [BANNER]
  for (const name of names) {
    lines.push(`export { ${name} } from './${name}/index.js'\n`)
  }
  await emit(join(config.output.dir, 'index.js'), lines.join(''), stats)
}

/**
 * Emit a `.d.ts` that points back at the user's config and lets tsc infer.
 *
 * Velite and content-collections converged on this independently, and it is the
 * sharpest idea in either: a handful of lines instead of a generated type tree,
 * it can never desync from the config, and it infers correctly through
 * arbitrary async transforms.
 */
export async function emitTypes(config: ResolvedConfig, stats: EmitStats): Promise<void> {
  if (config.output.types === false) return

  const rel = toPosix(relative(config.output.dir, config.configPath))
  const spec = rel.startsWith('.') ? rel : `./${rel}`
  const lines = [
    BANNER,
    `import type __config from ${JSON.stringify(spec)}\n`,
    `import type { InferDoc, InferIndex, Query } from 'contentmap'\n\n`
  ]
  for (const [name, def] of Object.entries(config.collections)) {
    const type = def.typeName ?? name
    lines.push(`export type ${type} = InferDoc<typeof __config, ${JSON.stringify(name)}>\n`)
    if (def.single) {
      // A singleton is one document, not a queryable collection.
      lines.push(`export declare const ${name}: ${type}\n\n`)
      continue
    }
    lines.push(`export type ${type}Index = InferIndex<typeof __config, ${JSON.stringify(name)}>\n`)
    lines.push(`export declare const ${name}: Query<${type}, keyof ${type}Index>\n\n`)
  }
  lines.push('export {}\n')
  await emit(join(config.output.dir, 'index.d.ts'), lines.join(''), stats)
}

/**
 * Remove generated output, and only that.
 *
 * The caches default to living inside the output directory, so a blanket rm
 * takes them too. That makes `build --clean --frozen` — two flags this project
 * documents for CI — destroy each other: clean discards the only copy of the
 * remote content, then frozen forbids fetching it again. Cache correctness is
 * guaranteed by content digests rather than by freshness of the directory, so
 * keeping it across a clean is safe as well as faster.
 */
export async function cleanOutput(config: ResolvedConfig): Promise<void> {
  const { dir, cacheDir } = config.output
  const nested = cacheDir === dir || cacheDir.startsWith(dir + sep)
  if (!nested) {
    await rm(dir, { recursive: true, force: true })
    return
  }

  // The cache is inside the output directory: remove the siblings around it.
  const keep = relative(dir, cacheDir).split(sep)[0]
  let entries: string[]
  try {
    entries = await readdir(dir)
  } catch {
    return // nothing to clean
  }
  await Promise.all(
    entries
      .filter(entry => entry !== keep)
      .map(entry => rm(join(dir, entry), { recursive: true, force: true }))
  )
}
