import { constants } from 'node:fs'
import { access, mkdir, readdir, readFile, rename, rm, writeFile } from 'node:fs/promises'
import { basename, dirname, join, relative } from 'node:path'
import type { CollectionDefinition, ResolvedConfig, StoreEntry } from '../types.ts'
import { digest } from '../utils/digest.ts'
import { withFdRetry } from '../utils/fd.ts'
import { mapLimit } from '../utils/limit.ts'
import { toPosix } from '../utils/paths.ts'
import { moduleNameFor, serialize, serializeAt } from './serialize.ts'

export interface EmitStats {
  written: number
  skipped: number
  /**
   * Digest of the content last written to each path, plus the source digest
   * that produced it. Lets a rebuild skip serialization entirely for documents
   * whose source has not changed — without it, an incremental build still pays
   * to re-serialize and re-read the whole corpus, which is precisely why a
   * one-character edit costs content-collections ~2 seconds.
   */
  emitted: Map<string, string>
  sources: Map<string, string>
  /** Serialized index-row fragments, keyed by output path. */
  rows: Map<string, string>
}

export function createEmitStats(): EmitStats {
  return { written: 0, skipped: 0, emitted: new Map(), sources: new Map(), rows: new Map() }
}

/**
 * Write output, skipping files whose bytes are unchanged.
 *
 * The skip matters for DX, not just speed: rewriting an identical file bumps
 * its mtime, which makes Vite and Next fire a spurious HMR update. We also
 * probe with access() rather than trusting an in-memory record — velite's
 * emitted-map is memory-only, so a file deleted outside the process is never
 * restored.
 */
export async function emit(
  path: string,
  content: string,
  stats: EmitStats,
  present?: ReadonlySet<string>
): Promise<void> {
  const hash = digest(content)
  if (stats.emitted.get(path) === hash) {
    // We wrote exactly these bytes this session. Confirm the file is still
    // there — velite trusts an in-memory map alone, so a file deleted outside
    // the process is never restored — but skip the far costlier read+compare.
    const there = present ? present.has(basename(path)) : await exists(path)
    if (there) {
      stats.skipped++
      return
    }
  } else {
    try {
      if ((await withFdRetry(() => readFile(path, 'utf8'))) === content) {
        stats.emitted.set(path, hash)
        stats.skipped++
        return
      }
    } catch {
      // missing or unreadable — fall through and write
    }
  }
  await mkdir(dirname(path), { recursive: true })
  const tmp = `${path}.${process.pid}.tmp`
  await withFdRetry(() => writeFile(tmp, content, 'utf8'))
  await rename(tmp, path)
  stats.emitted.set(path, hash)
  stats.written++
}

export async function exists(path: string): Promise<boolean> {
  try {
    await access(path, constants.F_OK)
    return true
  } catch {
    return false
  }
}

const BANNER = '// Generated by contentmap. Do not edit.\n'

/** Writes are cheaper than reads; the same bound keeps descriptors in check. */
const WRITE_CONCURRENCY = 64

function splitFields(
  entry: StoreEntry,
  collection: CollectionDefinition
): { index: Record<string, unknown>; full: Record<string, unknown> } {
  const heavy = new Set(collection.heavy ?? [])
  const allow = collection.index ? new Set(collection.index) : undefined
  // The document module carries full provenance; the index carries only what a
  // list view plausibly needs. `digest` is build-internal and must never ship,
  // and fileName/directory/extension are all derivable from filePath — at 5,000
  // documents those four fields alone dominated the index.
  const { digest: _digest, ...meta } = entry.meta
  const full: Record<string, unknown> = { ...entry.data, _meta: meta }
  const index: Record<string, unknown> = {}
  for (const [k, v] of Object.entries(entry.data)) {
    if (heavy.has(k)) continue
    if (allow && !allow.has(k)) continue
    index[k] = v
  }
  index['_meta'] = {
    id: meta.id,
    path: meta.path,
    slug: meta.slug,
    filePath: meta.filePath
  }
  return { index, full }
}

export interface EmitCollectionInput {
  collection: CollectionDefinition
  entries: readonly StoreEntry[]
  config: ResolvedConfig
  stats: EmitStats
}

/** One module per document plus a thin index that lazily imports them. */
export async function emitCollection({
  collection,
  entries,
  config,
  stats
}: EmitCollectionInput): Promise<void> {
  const dir = join(config.output.dir, collection.name)
  await mkdir(dir, { recursive: true })

  // One readdir replaces one access() per document. On a 10k corpus that is a
  // single syscall instead of ten thousand, and it still catches files deleted
  // outside the process — which is the reason we verify at all.
  const present = new Set<string>(await withFdRetry(() => readdir(dir)).catch(() => []))
  const format = collection.format ?? config.output.format
  const emitModules = format === 'modules' || format === 'both'
  const indexRows: string[] = []
  const loaders: string[] = []

  const work = entries.map(entry => {
    const mod = moduleNameFor(entry.id)
    const path = join(dir, `${mod}.js`)
    const fresh = stats.sources.get(path) !== entry.digest

    // Reuse the serialized index fragment when the source is unchanged. This is
    // what makes an incremental rebuild cost one row rather than the corpus.
    let row = fresh ? undefined : stats.rows.get(path)
    let full: Record<string, unknown> | undefined
    if (row === undefined) {
      const split = splitFields(entry, collection)
      full = split.full
      row = serializeAt(split.index, 1)
      stats.rows.set(path, row)
    }
    indexRows.push(row)
    if (!emitModules) return undefined
    loaders.push(`  ${JSON.stringify(entry.id)}: () => import('./${mod}.js')`)
    return { entry, full, path }
  })

  if (emitModules) {
    // Bounded-parallel, not serial. Ten thousand sequential awaits was 88% of a
    // cold build; the filesystem is happy to take these concurrently.
    await mapLimit(work, WRITE_CONCURRENCY, async item => {
      if (!item) return
      // Output is a pure function of the source, so an unchanged source digest
      // means unchanged output. Skipping serialize here keeps an incremental
      // rebuild proportional to what changed, not to corpus size.
      if (
        stats.sources.get(item.path) === item.entry.digest &&
        present.has(basename(item.path))
      ) {
        stats.skipped++
        return
      }
      const full = item.full ?? splitFields(item.entry, collection).full
      await emit(item.path, `${BANNER}export default ${serialize(full)}\n`, stats, present)
      stats.sources.set(item.path, item.entry.digest)
    })
  }

  const parts = [BANNER]
  if (emitModules) {
    parts.push(`import { collection } from 'contentmap/runtime'\n\n`)
    parts.push(`const index = [\n${indexRows.join(',\n')}\n]\n\n`)
    parts.push(`const modules = {\n${loaders.join(',\n')}\n}\n\n`)
    parts.push(`export const ${collection.name} = collection(index, modules)\n`)
    parts.push(`export default ${collection.name}\n`)
  } else {
    const rows = entries.map(e => splitFields(e, collection).full)
    parts.push(`export const ${collection.name} = ${serialize(rows)}\n`)
    parts.push(`export default ${collection.name}\n`)
  }
  await emit(join(dir, 'index.js'), parts.join(''), stats)
}

export async function emitBarrel(config: ResolvedConfig, stats: EmitStats): Promise<void> {
  const names = Object.keys(config.collections)
  const lines = [BANNER]
  for (const name of names) {
    lines.push(`export { ${name} } from './${name}/index.js'\n`)
  }
  await emit(join(config.output.dir, 'index.js'), lines.join(''), stats)
}

/**
 * Emit a `.d.ts` that points back at the user's config and lets tsc infer.
 *
 * Velite and content-collections converged on this independently, and it is the
 * sharpest idea in either: a handful of lines instead of a generated type tree,
 * it can never desync from the config, and it infers correctly through
 * arbitrary async transforms.
 */
export async function emitTypes(config: ResolvedConfig, stats: EmitStats): Promise<void> {
  if (config.output.types === false) return

  const rel = toPosix(relative(config.output.dir, config.configPath))
  const spec = rel.startsWith('.') ? rel : `./${rel}`
  const lines = [
    BANNER,
    `import type __config from ${JSON.stringify(spec)}\n`,
    `import type { InferDoc, InferIndex, Query } from 'contentmap'\n\n`
  ]
  for (const [name, def] of Object.entries(config.collections)) {
    const type = def.typeName ?? name
    lines.push(`export type ${type} = InferDoc<typeof __config, ${JSON.stringify(name)}>\n`)
    lines.push(
      `export type ${type}Index = InferIndex<typeof __config, ${JSON.stringify(name)}>\n`
    )
    lines.push(`export declare const ${name}: Query<${type}, keyof ${type}Index>\n\n`)
  }
  lines.push('export {}\n')
  await emit(join(config.output.dir, 'index.d.ts'), lines.join(''), stats)
}

export async function cleanOutput(config: ResolvedConfig): Promise<void> {
  await rm(config.output.dir, { recursive: true, force: true })
}
